### ISSUE TITLE
Allow adding arbitrary arguments to the pandoc invocation (for basic citation support)

### ISSUE THREAD

**Issue by OliverBalfour** [OliverBalfour/obsidian-pandoc#26]
Relates to #21 - this is a quick intermediate fix to support citations, at the cost of being slightly less user friendly (docs can help though).

The idea is there should be a setting where you can add stuff like this to the command (from SkepticMystic):

```
--citeproc --csl "https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl" 
--bibliography "Zotero Exports\My Library.json" 
--reference-doc="Pandoc\Templates\APA7.docx" 
```

**Comment by mafsi** [comment]
We  need to add only `--template` since bibliography and citation styles can be managed via `yaml`

```yaml
bibliography: [absolute/path/file.bib]
csl: [absolute/path/file.csl]
```

**Comment by OliverBalfour** [comment]
Done! If anyone has any problems just let me know.

**Comment by tim-hilde** [comment]
How is supposed to work? I've added ´´--citeproc --csl /Users/tim/Documents/Wissensmanagement/Pandoc/chicago.csl --bibliography /Users/tim/Documents/Wissensmanagement/Pandoc/lib.json``` to the settings but nothing is happening.

**Comment by OliverBalfour** [comment]
Hmm really? If you add eg `--template letter` that should work. I think the issue with citations is Pandoc only recognises the syntax in markdown, and my plugin uses HTML instead of markdown as the input format. So `--citeproc` option is recognised but does nothing. If that's the problem, I might add an option to export from HTML/markdown. The former will support DataView tables etc and the latter will support citations. Long term I'll think of a cleaner way to fix this

**Comment by tim-hilde** [comment]
That means not citation is possible at the moment? Tried the approach by @mafsi but it still doesn't work

**Comment by OliverBalfour** [comment]
@tim-hilde it would, *but* I've just pushed a temporary workaround to [version 0.2.1](https://github.com/OliverBalfour/obsidian-pandoc/releases/tag/0.2.1). I don't remember the citation syntax so I haven't tested it, but it basically adds a new option "Export files from HTML or markdown?" which if you set to markdown *should* (:crossed_fingers:) support citations. However, currently you can get either citations, or plugins features + links + file embeds unfortunately

**Comment by mafsi** [comment]
> 
> 
> That means not citation is possible at the moment? Tried the approach by @mafsi but it still doesn't work

Bibliography & Citation is managed already by pandoc via YAML. This is what I intended to say.
See here: https://forum.obsidian.md/t/share-your-zettel-note-template/3961/50

**Comment by OliverBalfour** [comment]
Yes, it is. The issue is that the citation syntax works if you use a markdown input to Pandoc, but my plugin uses an HTML input. I've added an option to use a markdown input which should make citations work but will break non-standard markdown syntax from eg DataView

**Comment by mafsi** [comment]
> 
> 
> Yes, it is. The issue is that the citation syntax works if you use a markdown input to Pandoc, but my plugin uses an HTML input. I've added an option to use a markdown input which should make citations work but will break non-standard markdown syntax from eg DataView

Yeah, the problem with Obsidian Plugins is that they are far from standard. I like to keep as close to standar as possible for the ime when I will switch from Obsidian to other editor.

**Comment by OliverBalfour** [comment]
FYI @tim-hilde @mafsi I've added some documentation about getting citations working here (I actually tested it this time!):
https://github.com/OliverBalfour/obsidian-pandoc/wiki/Citations-(work-in-progress)
It's a little fiddly at this stage but it works for now

**Comment by tim-hilde** [comment]
This will probably work better when obsidian introduces their "export to standard markdown" functionality
